package com.ch14;

public class Exception_2 {
	/*
	 * 메소드 뒤에 throws를 붙이면 예외처리를 나를 호출한 곳에서
	 * 처리 받아라 ... 의미
	 */
	void methodA() throws Exception{
		System.out.println("methodA 호출");
	}
	/*
	 * try..catch블록은 예외상황이 발생했을 경우에만 효과가 있다.
	 * 예외상황이 없다면 있으나 마나한 코드
	 * 
	 */
	public static void main(String[] args) {
		Exception_2 exc1 = null;
		try {
			exc1.methodA();
		} catch(NumberFormatException ne) {
			System.out.println("Exception:"+ne.toString());
		} catch (Exception e) {
			System.out.println("Exception:"+e.toString());
		}

		System.out.println("다른 코드들.....");
	}

}
